language: go

go:
- 1.12.x

notifications:
  email: false

env:
  global:
    - GO111MODULE=on

before_install:
- '[ "${TRAVIS_PULL_REQUEST}" = "false" ] && openssl aes-256-cbc -K $encrypted_56d12e7424aa_key
  -iv $encrypted_56d12e7424aa_iv -in .env.enc -out .env -d || true'
- nvm install 12
- npm install -g npm@6.x
- sudo apt-get update
- sudo apt-get install python
- go get -u gopkg.in/alecthomas/gometalinter.v2
- go get -u golang.org/x/lint/golint

install:
- if [ "${TRAVIS_TAG}" = "${TRAVIS_BRANCH}" ]; then cd appscan; make asoc-tool; cd
  ../; fi

before_script:
- if [ "${TRAVIS_TAG}" = "${TRAVIS_BRANCH}" ]; then chmod a+x ./appscan/ASOC.sh; fi

script:
- go test `go list ./... | grep -v examples`
- go test `go list ./... | grep -v core` -v -tags=integration
- gometalinter.v2 --errors ./...
- if [ "${TRAVIS_TAG}" = "${TRAVIS_BRANCH}" ]; then ./appscan/ASOC.sh; fi

before_deploy:
- pip install --user bumpversion
- npm install @semantic-release/changelog
- npm install @semantic-release/exec
- npm install @semantic-release/git
- npm install @semantic-release/github

deploy:
- provider: script
  skip_cleanup: true
  script: npx semantic-release --repository-url https://${GH_TOKEN}@github.com/watson-developer-cloud/go-sdk
    --debug
